#!/bin/bash

# Usage: call this script from the tangent directory to run a search
# using the default databse directory, or optionally a different
# directory.

INITIAL_OUTPUT="results-db-index.tsv"

echo "Retrieving expressions...."
if [ $# -lt 1 ]
then
	echo "S" | cat db-index/* - | ./mathindex.exe  > $INITIAL_OUTPUT
else
	if [ $# -gt 0 ]
	then
		INITIAL_OUTPUT="results-$1.tsv"
		echo "S" | cat $1/* - | ./mathindex.exe > $INITIAL_OUTPUT
	fi
fi

echo "done."

